---
title: "Desenvolvimento de Modelos em Python"
author: "Ramon Moreno Ferrari em "
date: "`r format(Sys.time(), '%d/%m/%Y')`"
output: github_document #output RMD
# Para output PDF/Latex, comentar acima e descomentar abaixo:
#
#fontfamily: lmodern #https://tug.org/FontCatalogue/seriffonts.html
#header-includes:
#  - \usepackage{graphicx}
#  - \usepackage{fancyhdr}
#  - \usepackage[T1]{fontenc}
#  - \usepackage[default]{sourcesanspro}
#  - \usepackage{lmodern}
#  - \input{preamble}  
#  - \pagestyle{mystyle}
#  - \hypersetup{pageanchor=false}
#output: 
#  pdf_document:
#    keep_tex: true
---
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
```

```{r,warning=FALSE,message=FALSE,include=FALSE}
library(tidyverse)
library(knitr)
library(showtext)
font_add_google(name = "Roboto Slab",family = "Roboto") # https://fonts.google.com/?sort=popularity
```

## Baixando o dado
```{python}
import pandas as pd
import numpy as np
url='https://raw.githubusercontent.com/ramonferrari/r_and_python/main/intro_python_files/imports-85.data'
df=pd.read_csv(url,header=None)
df
headers = ["symboling","normalized-losses","make","fuel-type","aspiration", "num-of-doors","body-style", "drive-wheels","engine-location","wheel-base", "length","width","height","curb-weight","engine-type", "num-of-cylinders", "engine-size","fuel-system","bore","stroke","compression-ratio","horsepower", "peak-rpm","city-mpg","highway-mpg","price"]
df.columns=headers
df["normalized-losses"]=df["normalized-losses"].replace("?",np.nan) # trocamos ? por NaN
df['normalized-losses'] = df['normalized-losses'].astype(float) # convertermos de string para float
df["price"]=df["price"].replace("?",np.nan) # trocamos ? por NaN
df['price'] = df['price'].astype(float) # convertermos de string para float
df["city-mpg"]=235/df["city-mpg"]
df.rename(columns={"city-mpg":"city-L/100km"},inplace=True)
df.dropna(axis=0,inplace=True) # mesmo acima, ja substituindo o dataset df
df
df.dtypes
```
